base_url = "https://loud.rs"
title = "Loud"
description = "Loud 是一个小而强大的博客平台"
author = "anqr"
theme = "juice"
compile_sass = true
build_search_index = false
default_language = "zh"

[languages.en]
title = "Loud"
description = "Loud is a small and powerful blog platform, it is a dynamic blog based on Rust, it uses Markdown as the main content format."

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
juice_logo_path = "logo.svg"
juice_logo_name = "Loud"
repository_url = "https://github.com/loud-rs/loud"
juice_extra_menu = [
    { title = "Gitee", link = "https://gitee.com/loud-rs/loud"},
    { title = "Github", link = "https://github.com/loud-rs/loud"},
]
juice_exclude_menu = [
    "Showcases",
    "exclude_from_nav",
]