# The URL the site will be built for
base_url = "https://loud.rs"

# Setting the default theme
theme = "juice"

# The title of the site
title = "Loud - A small yet potent Rust blog platform"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
juice_logo_path = "logo.svg"
juice_logo_name = "Loud"
repository_url = "https://github.com/loud-rs/loud"
juice_extra_menu = [
    { title = "Gitee", link = "https://gitee.com/loud-rs/loud"},
    { title = "Github", link = "https://github.com/loud-rs/loud"},
]
juice_exclude_menu = [
    "Showcases",
    "exclude_from_nav",
]